name: build
on:
  push:
    paths-ignore:
      - 'problems/**'
      - 'resources/**'
      - 'solutions-cpp/**'
      - '.gitignore'
      - 'CONTRIBUTING.md'
      - 'LICENSE'
      - 'README.md'
    branches: [main]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Gradle - Build / Test / Sonar tasks
        run: cd solutions-java ; gradle clean build sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}